### ISSUE TITLE
Running as background on screen does not work with Plasma KDE

### ISSUE THREAD

**Issue by danbulant** [Almamu/linux-wallpaperengine#25] opened 2020-07-30 09:21 UTC
Running it without `--screen-root` works as expected (opens window), but when running with it, wallpaper does not change (Plasma still shows default wallpaper). No error output - looks like Plasma just overwrites the wallpaper (or something else is happenning?).

Output is same as with running without `-screen-root` (except on start, there's new `Found requested screen: eDP-1 -? 0x0:1366x768`.

**Comment by Almamu** [comment] 2020-07-30 12:14
Support for desktop wallpaper drawing is finicky at best. Right now It will only work on non-composited root windows if nothing else is drawing to it. This is in the TODO list but It would be better to get more compatibility with wallpapers first, so It's kind of low priority right now, of course any help with this is welcome. #8

**Comment by chenxiaoquan233** [comment] 2020-08-18 14:00
the same with gnome on ubuntu20.04

**Comment by Almamu** [comment] 2020-08-24 15:57
I'll close this one as It's a duplicate of #8, feel free to report on what desktop environments it doesn't work on that issue so we can compile a list and gradually add support for them.

**Closed by Almamu** 2020-08-24 15:57 UTC
Labels: bug, duplicate
