### ISSUE TITLE
how to  run as a screen's background?

### ISSUE THREAD

**Issue by HaHadaxigua** [Almamu/linux-wallpaperengine#126] opened 2022-08-13 04:03 UTC
The readme says 'Only screens configured with the XRandr extension are supported'.

But it dosen't work for my ubuntu22.04. 

Here is my setup.

I run this command first:
```shell
xrandr --output DP-1-2 --mode 3840x2160
```
and then
```
wallengine 1143394477 --screen-root DP-1-2
```

the output is:
```
No scene.pkg file found at /home/dh/.local/share/Steam/steamapps/workshop/content/431960/1143394477/. Defaulting to normal folder storage
No gifscene.pkg file found at /home/dh/.local/share/Steam/steamapps/workshop/content/431960/1143394477/. Defaulting to normal folder storage
Found wallpaper engine's assets at /home/dh/.local/share/Steam/steamapps/common/wallpaper_engine/assets
Found requested screen: DP-1-2 -> 7296x0:2160x3840
```

Is there any problem with my command? 

And It can preview in window correctly.

Plz tell me whats wrong with my setup. Thank you very much

**Comment by Lin2D2** [comment] 2022-08-15 20:56
I Have the same issue:
```
./wallengine --fps 15 --screen-root DP-0 --screen-root DP-2 /home/space/.steam/debian-installation/steamapps/workshop/content/431960/1169486096

Detected scene.pkg file at /home/space/.steam/debian-installation/steamapps/workshop/content/431960/1169486096/scene.pkg. Adding to list of searchable paths
No gifscene.pkg file found at /home/space/.steam/debian-installation/steamapps/workshop/content/431960/1169486096/. Defaulting to normal folder storage
Found wallpaper engine's assets at /home/space/.steam/debian-installation/steamapps/common/wallpaper_engine/assets
cameraparallaxmouseinfluence is not of type double, returning default value
camerashakeroughness is not of type double, returning default value
camerashakespeed is not of type double, returning default value
Found requested screen: DP-0 -> 0x0:2560x1440
Found requested screen: DP-2 -> 2560x360:1920x1080
```

But nothing shows on screen, but when i run in window mode it works

**Comment by AsessionGuy** [comment] 2022-08-31 00:23
> But it dosen't work for my ubuntu22.04.

Do you have gnome?

**Comment by Almamu** [comment] 2022-11-03 23:41
@Lin2D2 @HaHadaxigua Right now it doesn't work with GNOME or KDE as these DE tend to take over the control of the background and they forcefully draw over anything that might be drawing there. Closing as duplicate of #8

**Closed by Almamu** 2022-11-03 23:41 UTC
